// Generated by view binder compiler. Do not edit!
package com.tamweenk.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.tamweenk.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHellotamweenkBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button button2;

  @NonNull
  public final EditText editTextTextPersonName4;

  @NonNull
  public final EditText editTextTextPersonName5;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final TextView textView2;

  private ActivityHellotamweenkBinding(@NonNull ConstraintLayout rootView, @NonNull Button button2,
      @NonNull EditText editTextTextPersonName4, @NonNull EditText editTextTextPersonName5,
      @NonNull ImageView imageView3, @NonNull TextView textView2) {
    this.rootView = rootView;
    this.button2 = button2;
    this.editTextTextPersonName4 = editTextTextPersonName4;
    this.editTextTextPersonName5 = editTextTextPersonName5;
    this.imageView3 = imageView3;
    this.textView2 = textView2;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHellotamweenkBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHellotamweenkBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_hellotamweenk, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHellotamweenkBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button2;
      Button button2 = ViewBindings.findChildViewById(rootView, id);
      if (button2 == null) {
        break missingId;
      }

      id = R.id.editTextTextPersonName4;
      EditText editTextTextPersonName4 = ViewBindings.findChildViewById(rootView, id);
      if (editTextTextPersonName4 == null) {
        break missingId;
      }

      id = R.id.editTextTextPersonName5;
      EditText editTextTextPersonName5 = ViewBindings.findChildViewById(rootView, id);
      if (editTextTextPersonName5 == null) {
        break missingId;
      }

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      return new ActivityHellotamweenkBinding((ConstraintLayout) rootView, button2,
          editTextTextPersonName4, editTextTextPersonName5, imageView3, textView2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
